spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username:
    password:
    driverClassName: org.h2.Driver
  application:
    name: openweathermap

api:
  weather:
    service-url: http://api.openweathermap.org/data/2.5/weather/
    units: metric
    app-id:

management:
  endpoints:
  enabled-by-default: false
  endpoint:
    health:
      enabled: true
#TODO configure security add tests
